Repository mediathekview/MServer, pull requests merged in 2023-10, with the labels that each got.

#924 SRF remove changing url parameters in m3u8 files
  src/main/java/mServer/crawler/sender/srf/parser/SrfFilmJsonDeserializer.java
Labels: Fertig, hacktoberfest-accepted

#931 update crawler overview
  README.md
Labels: hacktoberfest-accepted

#927 Dev/livestream import
  MServer-Config.yaml
  src/main/java/de/mediathekview/mserver/base/config/ImportLivestreamConfiguration.java
  src/main/java/de/mediathekview/mserver/base/config/MServerConfigDTO.java
  src/main/java/de/mediathekview/mserver/crawler/CrawlerManager.java
  src/main/java/de/mediathekview/mserver/ui/config/MServerConfigUI.java
  src/main/resources/MServer-Config.yaml
  src/main/resources/live-streams.json
  src/test/java/de/mediathekview/mserver/crawler/CrawlerManagerLivestreamTest.java
  src/test/java/de/mediathekview/mserver/crawler/CrawlerManagerTest.java
  src/test/resources/MServer-JUnit-Config.yaml
  src/test/resources/MediathekView_Messages_de_DE.properties
  src/test/resources/filmlists/livestream/live-streams.json
  src/test/resources/filmlists/livestream/live-streams.json.bz
  src/test/resources/filmlists/livestream/live-streams.json.gz
  src/test/resources/filmlists/livestream/live-streams.json.xz
  src/test/resources/filmlists/livestream/live-streams_old.json
  src/test/resources/filmlists/livestream/live-streams_old.json.bz
  src/test/resources/filmlists/livestream/live-streams_old.json.gz
  src/test/resources/filmlists/livestream/live-streams_old.json.xz
Labels: enhancement, in progress
